name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install FTP client
        run: sudo apt-get install -y lftp

      - name: Deploy to InfinityFree via FTP
        env:
          FTP_HOST: ftpupload.net
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -d -e "
          set ftp:passive-mode on
          open -u \$FTP_USERNAME,\$FTP_PASSWORD \$FTP_HOST
          mirror -R --ignore-time ./ /htdocs
          quit
          " || exit 1
